# -*- coding: utf-8 -*-
"""minor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pIezQ1QziNsgoABfkVY4hT5Xt9eXaqB8
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/arib168/data/main/50_Startups.csv")

df

df.info()

df.isnull().sum()

profit = df.select_dtypes(include=['int64','float64'])
profit

profit.info()

profit.isnull().sum()

profit.shape

profit.columns

profit.nunique()

profit["R&D Spend"].nunique()

x = profit.iloc[:,0:3].values
x

y = profit.iloc[:,-1].values
y

x.shape

y.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.75,random_state=10)

0.75*50

x_train.shape

y_train.shape

x_test.shape

y_test.shape

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

y_pred



from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

import matplotlib.pyplot as plt 
plt.plot(y_test,y_pred,c='b',label = 'Hypothesis') 
plt.legend()
plt.show()

"""GRAPHS"""

import matplotlib.pyplot as plt

x1 = df.iloc[:,0].values
x2 = df.iloc[:,1].values
x3 = df.iloc[:,2].values
x4 = df.iloc[:,3].values
x5 = df.iloc[:,4].values

plt.title("MATPLOTLIB LINE GRAPH",fontsize=10)
plt.plot(x1,x2,color='red',label = 'Line 1',marker = "o")
plt.plot(x1,x3,color='blue',label = 'Line 2')
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.grid()
plt.legend()
plt.show()

df.plot()
plt.show()

df.plot(kind = 'scatter', x = 'Administration', y = 'Profit')
plt.show()

df["Profit"].plot(kind = 'hist')

import seaborn as sns
sns.distplot(x3)

sns.distplot(x2)

plt.style.use("dark_background")
sns.distplot(df.Administration, bins=20, color="g")
plt.title("Administration", fontsize=20, color = 'red')
plt.show()

plt.style.use("classic")
sns.distplot(x1, bins=20, color="g")
plt.title("R&D Spend", fontsize=20, color = 'red')
plt.show()

# to show the relationship between variables
corelation = df.corr()

sns.heatmap(corelation,xticklabels = corelation.columns,yticklabels = corelation.columns,annot=True )

corelation1 = profit.corr()

sns.heatmap(corelation,xticklabels = corelation.columns,yticklabels = corelation.columns,annot=True )

sns.pairplot(profit)

sns.relplot(x=x3,y=x5,hue=x4,data=profit)

sns.catplot(x=x2,kind="box",data=profit)









































































